import type { Metadata } from "next";
import { Geist, Geist_Mono,  Roboto } from "next/font/google";

import "./globals.css";
// import './workspace'

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100","300","400","500","700","900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"><head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Momo+Trust+Display&display=swap"
        />
      </head>
      <body
        className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
