// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ variable: "--font-roboto", subsets: ["latin"], weight: ["400", "700"] });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: { icon: "/images/logo/logo.svg" } // optional fallback
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon for all browsers */}
        <link rel="icon" href="/images/logo/logo.svg" type="image/svg+xml" />
        {/* Optional: fallback for older browsers */}
        <link rel="shortcut icon" href="/images/logo/logo.ico" type="image/x-icon" />
      </head>
      <body className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
